Nft
Satangtech/merchant-wallet-sdk pull request #2
Opened 2023-04-05 09:04 UTC by Ic3Sandy

2023-04-11 13:00 UTC, thebevrishot requested changes
Seem like we missing some methods from standard 
`https://eips.ethereum.org/EIPS/eip-1155`
and `https://eips.ethereum.org/EIPS/eip-721`

And we could not use number to represent uint256 for solidity since it's exceed size of safe integer(It would be convert to float)

2023-04-11 13:00 UTC, thebevrishot commented on lib/merchant-wallet.ts
> +  async safeTransferFromERC721(
Do we need to the return type here?

2023-04-11 13:00 UTC, thebevrishot commented on lib/merchant-wallet.ts
> +      .safeTransferFrom(from, to, tokenId)
Do `safeTransferFrom` accept data as the forth field?

2023-04-11 13:00 UTC, thebevrishot commented on lib/merchant-wallet.ts
> +  }
Missign the field `getApprovedERC721`?

2023-04-11 13:00 UTC, thebevrishot commented on lib/merchant-wallet.ts
> +  }
`isApprovedForAllERC721` also?

2023-04-11 13:00 UTC, thebevrishot commented on lib/merchant-wallet.ts
> +    tokenIds: number[],
String?

2023-04-18 02:46 UTC, Ic3Sandy commented on lib/merchant-wallet.ts
> +  async safeTransferFromERC721(
Ok krub, I will add the return type.

2023-04-18 02:51 UTC, Ic3Sandy commented on lib/merchant-wallet.ts
> +      .safeTransferFrom(from, to, tokenId)
yes, I will add data with default value for the forth field

2023-04-18 02:56 UTC, Ic3Sandy commented on lib/merchant-wallet.ts
> +  }
I didn't add those method because I think it not relate with merchant wallet

2023-04-18 02:59 UTC, Ic3Sandy commented on lib/merchant-wallet.ts
> +  }
`function getApproved(uint256 _tokenId) external view returns (address);`

It receive tokenId I not sure to add function like this to merchant wallet

2023-04-18 03:00 UTC, Ic3Sandy commented on lib/merchant-wallet.ts
> +    tokenIds: number[],
I see krub, I will change it to string krub

2023-04-26 04:26 UTC, tanakornon commented
LGTM

2023-04-26 04:50 UTC, merged